### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Kharg** [mozkomor05/espocrm-comments-extension#1]
On Espo 7.1.11 with php 8.1 I am getting a Maximum call stack size exceeded error.
Also AfterInstall and AfterUninstall scripts are missing from the extension.
![image](https://user-images.githubusercontent.com/32223252/186735386-3ed5e20f-8439-4d5f-80bb-86379b41d330.png)

**Comment by mozkomor05** [comment]
Thanks for reporting. This is caused by the `extender.js` script, which most likely works only with Espo 7.2 (which isn't even released yet :D). 

As for the install scripts - these script should not be necessary. In most of the extensions I published they usually contain only an example template.
